apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-devops-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: python-devops-monitor
  endpoints:
    - port: http
      path: /metrics
      interval: 15s